name: "Deploy"

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        if: ${{ startsWith(github.event.comment.body, '/deploy') }}
      
      - uses: actions/checkout@v2
        if: ${{ startsWith(github.event.comment.body, '/deploy') }}
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          
      - uses: actions/checkout@v2
        if: ${{ startsWith(github.event.comment.body, '/deploy2') }}
        
      - run: ls
  
  build:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - run: ls
