name: "Deploy"

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #checkout
      - name: "Use pull-request-comment-branch action"
        uses: xt0rted/pull-request-comment-branch@v1
        if: ${{ startsWith(github.event.comment.body, '/deploy') }}
      
      - name: "Checkout to ${{ steps.comment-branch.outputs.head_ref }}"
        uses: actions/checkout@v2
        if: ${{ startsWith(github.event.comment.body, '/deploy') }}
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          
      - name: "Checkout tot {{github.head_ref}}"
        uses: actions/checkout@v2
        if: ${{ startsWith(github.event.comment.body, '/deploy2') }}
      #checkout
      - run: ls
