name: "Deploy"

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  checkoutOnComment:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.comment.body, '/deploy') }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          
      - run: ls
  checkoutOnApprove:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.comment.body, '/deploy2') }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      
      - uses: actions/checkout@v2
          
      - run: ls
      
  build:
    runs-on: ubuntu-lates
    needs: [checkoutOnComment, checkoutOnApprove]
    steps:
      - run: ls
