name: "Deploy"

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.comment.body, '/deploy') }}
    steps:
      - uses: actions/checkout@v2

      - name: test
        run: echo "${toJson(github.event)}"
